name: CI — Build & Publish multi-target images

on:
  push:
    branches: [ main, master ]

env:
  IMAGE_NAME: tts_app
  DOCKER_NAMESPACE: ${{ vars.DOCKER_NAMESPACE }}  

jobs:
  build-multi-target:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [ serverless, pod ]
      fail-fast: false
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image for target ${{ matrix.target }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ matrix.target }}
            ${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ matrix.target }}-${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
